app = "wild-minio"
primary_region = "gru"

[mounts]
source = "miniodata"
destination = "/data"

[http_service]
	internal_port = 9000
	force_https = true
	auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
